name: giveaway
description: Miniproject 2 RamalakshmiJothiram.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  foldable_sidebar: ^1.0.0
  shared_preferences: ^0.5.12
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5

  google_sign_in: ^4.5.4
  font_awesome_flutter: ^8.8.1
  firebase_core: "0.5.0"
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^0.3.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
 
  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
  - assets/g.png
